print("enter number: ")
x = int(input())
print("0", "x" , x , "=" , x*0)
print("1", "x" , x , "=" , x*1)
print("2", "x" , x , "=" , x*2)
print("3", "x" , x , "=" , x*3)
print("4", "x" , x , "=" , x*4)
print("5", "x" , x , "=" , x*5)
print("6", "x" , x , "=" , x*6)
print("7", "x" , x , "=" , x*7)
print("8", "x" , x , "=" , x*8)
print("9", "x" , x , "=" , x*9)